### ISSUE TITLE
testdeletebyothers

### ISSUE THREAD

**Issue by lixzhang** [lixzhang/screenshots#4]
![aml access code_v2](https://cloud.githubusercontent.com/assets/9322661/11898656/76dd7da8-a567-11e5-82a3-a3173f801072.PNG)

**Comment by lixzhan** [comment]
test
![aml access code detail](https://cloud.githubusercontent.com/assets/14793231/11898707/03c2a248-a568-11e5-98bd-b42492b1a151.png)

**Comment by lixzhan** [comment]
additional issues after close

**Comment by lixzhang** [comment]
conclusion: 
owners can edit comments from everyone. 
non-owners can edit their own comments but not those from anybody else. 
additional comments can be added after an issue is closed.

**Comment by lxzhang03** [comment]
test if one user can change comments from another user, neither of whom are owners.

**Comment by lixzhan** [comment]
test if others get emails about one update.

what if I edit this, do others still get notified?

**Comment by lixzhan** [comment]
another test
